include:
  - docker-compose.dev.yml

services:
  svarog:
    image: markojerkic/svarog:latest
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - MONGO_URL=mongodb://svarog-mongodb:27017/
      - HTTP_SERVER_PORT=1323
      - NATS_ADDR=nats://nats:4222
      - NATS_ISSUER_SEED=${NATS_ISSUER_SEED}
      - NATS_JWT_SECRET=${NATS_JWT_SECRET}
      - NATS_SYSTEM_USER=${NATS_SYSTEM_USER}
      - NATS_SYSTEM_PASSWORD=${NATS_SYSTEM_PASSWORD}
      - NATS_APP_USER=${NATS_APP_USER}
      - NATS_APP_PASSWORD=${NATS_APP_PASSWORD}
    depends_on:
      - svarog-mongodb
      - nats
    develop:
      watch:
        - path: .
          target: builder
          action: rebuild
  nginx:
    image: nginx:alpine
    ports:
      - "1323:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - svarog
    restart: unless-stopped
